### PR TITLE
Fix duplicates

### PR DESCRIPTION
**Pull request by Mq89**
@tobi18991 Is this branch still necessary, or can it be removed?

### CODE REVIEW

**Comment by tobi18991** [comment]
It is still needed. However, the development has paused for a while.

Fixes #79.

**Comment by Mq89** [comment]
Do you plan to resume development soon?
What needs to be done to merge this branch into main?

**Comment by tobi18991** [comment]
As I'm having more time now, I plan to continue the development very soon. Unfortunately, I was on holidays for the last two weeks.

The problem is that this fix still causes some problems while rendering edges and nodes (at least that is what I remember from the last time working on this).

**Comment by tobi18991** [comment]
Somehow I found the remaining fix quite fast. The rendering of marked and selected edges should now work as expected without any duplicates shown after resizing attack graph nodes.

**Pull request merged**
